---
- hosts: all
  tasks:
    - name: 'Check mandatory variables are defined'
      assert:
        that:
          - dst_dir is defined
          - config_name is defined
          - v2fly_conf is defined

    - name: 'Create destination directory'
      file:
        path: '{{ dst_dir | mandatory }}'
        state: directory
      become: yes

    - name: 'Create compose file'
      template:
        src: ../docker-compose.yml.j2
        dest: '{{ dst_dir | mandatory }}/docker-compose.yml'
      become: yes

    - name: 'Create config.json'
      template:
        src: ../{{ config_name | mandatory }}.json.j2'
        dest: '{{ dst_dir | mandatory }}/{{ v2fly_conf | mandatory }}'
      become: yes

    - name: 'Pull images'
      shell: 'cd {{ dst_dir }} && docker-compose pull'
      become: yes

    - name: 'Stop containers'
      shell: 'cd {{ dst_dir }} && docker-compose down'
      become: yes

    - name: 'Start containers'
      shell: 'cd {{ dst_dir }} && docker-compose up -d'
      become: yes
