---
all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    dst_dir: ~/v2fly
  children:
    production:
      hosts:
        layer1:
          src_dir: ../layer1
          ansible_user: '{{ l1_user }}'
          ansible_host: '{{ l1_host }}'
          ansible_ssh_private_key_file: '{{ l1_ssh_key }}'
        layer2:
          src_dir: ../layer2
          ansible_user: '{{ l2_user }}'
          ansible_host: '{{ l2_host }}'
          ansible_ssh_pass: '{{ l2_ssh_pass }}'
